const listOfCurrencies = [
  { label: "Australia Dollar", value: "AUD" },
  { label: "Great Britain Pound", value: "GBP" },
  { label: "Euro", value: "EUR" },
  { label: "Japan Yen", value: "JPY" },
  { label: "Switzerland Franc", value: "CHF" },
  { label: "USA Dollar", value: "USD" },
  { label: "Nigeria Naira", value: "NGN" },
  { label: "Afghanistan Afghani", value: "AFN" },
  { label: "Albania Lek", value: "ALL" },
  { label: "Algeria Dinar", value: "DZD" },
  { label: "Angola Kwanza", value: "AOA" },
  { label: "Argentina Peso", value: "ARS" },
  { label: "Armenia Dram", value: "AMD" },
  { label: "Aruba Florin", value: "AWG" },
  { label: "Australia Dollar", value: "AUD" },
  { label: "Austria Schilling", value: "ATS" },
  { label: "Belgium Franc", value: "BEF" },
  { label: "Azerbaijan New Manat", value: "AZN" },
  { label: "Bahamas Dollar", value: "BSD" },
  { label: "Bahrain Dinar", value: "BHD" },
  { label: "Bangladesh Taka", value: "BDT" },
  { label: "Barbados Dollar", value: "BBD" },
  { label: "Belarus Ruble", value: "BYR" },
  { label: "Belize Dollar", value: "BZD" },
  { label: "Bermuda Dollar", value: "BMD" },
  { label: "Bhutan Ngultrum", value: "BTN" },
  { label: "Bolivia Boliviano", value: "BOB" },
  { label: "Bosnia Mark", value: "BAM" },
  { label: "Botswana Pula", value: "BWP" },
  { label: "Brazil Real", value: "BRL" },
  { label: "Great Britain Pound", value: "GBP" },
  { label: "Brunei Dollar", value: "BND" },
  { label: "Bulgaria Lev", value: "BGN" },
  { label: "Burundi Franc", value: "BIF" },
  { label: "CFA Franc BCEAO", value: "XOF" },
  { label: "CFA Franc BEAC", value: "XAF" },
  { label: "CFP Franc", value: "XPF" },
  { label: "Cambodia Riel", value: "KHR" },
  { label: "Canada Dollar", value: "CAD" },
  { label: "Cape Verde Escudo", value: "CVE" },
  { label: "Cayman Islands Dollar", value: "KYD" },
  { label: "Chili Peso", value: "CLP" },
  { label: "China Yuan/Renminbi", value: "CNY" },
  { label: "Colombia Peso", value: "COP" },
  { label: "Comoros Franc", value: "KMF" },
  { label: "Congo Franc", value: "CDF" },
  { label: "Costa Rica Colon", value: "CRC" },
  { label: "Croatia Kuna", value: "HRK" },
  { label: "Cuba Convertible Peso", value: "CUC" },
  { label: "Cuba Peso", value: "CUP" },
  { label: "Cyprus Pound", value: "CYP" },
  { label: "Czech Koruna", value: "CZK" },
  { label: "Denmark Krone", value: "DKK" },
  { label: "Djibouti Franc", value: "DJF" },
  { label: "Dominican Republich Peso", value: "DOP" },
  { label: "East Caribbean Dollar", value: "XCD" },
  { label: "Egypt Pound", value: "EGP" },
  { label: "El Salvador Colon", value: "SVC" },
  { label: "Estonia Kroon", value: "EEK" },
  { label: "Ethiopia Birr", value: "ETB" },
  { label: "Falkland Islands Pound", value: "FKP" },
  { label: "Finland Markka", value: "FIM" },
  { label: "Fiji Dollar", value: "FJD" },
  { label: "Gambia Dalasi", value: "GMD" },
  { label: "Georgia Lari", value: "GEL" },
  { label: "Germany Mark", value: "DMK" },
  { label: "Ghana New Cedi	", value: "GHS" },
  { label: "Gibraltar Pound", value: "GIP" },
  { label: "Greece Drachma", value: "GRD" },
  { label: "Guatemala Quetzal", value: "GTQ" },
  { label: "Guinea Franc", value: "GNF" },
  { label: "Guyana Dollar", value: "GYD" },
  { label: "Haiti Gourde", value: "HTG" },
  { label: "Honduras Lempira", value: "HNL" },
  { label: "Hong Kong Dollar", value: "HKD" },
  { label: "Hungary Forint", value: "HUF" },
  { label: "Iceland Krona", value: "ISK" },
  { label: "India Rupee", value: "INR" },
  { label: "Indonesia Rupiah", value: "IDR" },
  { label: "Iran Rial", value: "IRR" },
  { label: "Iraq Dinar", value: "IQD" },
  { label: "Ireland Pound", value: "IED" },
  { label: "Israel New Shekel", value: "ILS" },
  { label: "Italy Lira", value: "ITL" },
  { label: "Jamaica Dollar", value: "JMD" },
  { label: "Japan Yen", value: "JPY" },
  { label: "Jordan Dinar", value: "JOD" },
  { label: "Kazakhstan Tenge", value: "KZT" },
  { label: "Kenya Shilling", value: "KES" },
  { label: "Kuwait Dinar", value: "KWD" },
  { label: "Kyrgyzstan Som", value: "KGS" },
  { label: "Laos Kip", value: "LAK" },
  { label: "Euro", value: "EUR" },
  { label: "EuLatvia Latsro", value: "LVL" },
  { label: "Lebanon Pound", value: "LBP" },
  { label: "Lesotho Loti", value: "LSL" },
  { label: "Liberia Dollar", value: "LRD" },
  { label: "Libya Dinar", value: "LYD" },
  { label: "Lithuania Litas", value: "LTL" },
  { label: "Luxembourg Franc", value: "LUF" },
  { label: "Macau Pataca", value: "MOP" },
  { label: "Macedonia Denar", value: "MKD" },
  { label: "Malagasy Ariary", value: "MGA" },
  { label: "Malawi Kwacha", value: "MWK" },
  { label: "Malaysia Ringgit", value: "MYR" },
  { label: "Maldives Rufiyaa", value: "MVR" },
  { label: "Malta Lira", value: "MTL" },
  { label: "Mauritania Ouguiya", value: "MRO" },
  { label: "Mauritius Rupee", value: "MUR" },
  { label: "Mexico Peso", value: "MXN" },
  { label: "Moldova Leu", value: "MDL" },
  { label: "Mongolia Tugrik", value: "MNT" },
  { label: "Morocco Dirham", value: "MAD" },
  { label: "Mozambique New Metical", value: "MZN" },
  { label: "Myanmar Kyat", value: "MMK" },
  { label: "NL Antilles Guilder", value: "ANG" },
  { label: "Namibia Dollar", value: "NAD" },
  { label: "Nepal Rupee", value: "NPR" },
  { label: "Netherlands Guilder", value: "NLG" },
  { label: "New Zealand Dollar", value: "NZD" },
  { label: "Nicaragua Cordoba Oro", value: "NIO" },
  { label: "North Korea Won", value: "KPW" },
  { label: "Norway Kroner", value: "NOK" },
  { label: "Oman Rial", value: "OMR" },
  { label: "Pakistan Rupee", value: "PKR" },
  { label: "Panama Balboa", value: "PAB" },
  { label: "Papua New Guinea Kina", value: "PGK" },
  { label: "Paraguay Guarani", value: "PYG" },
  { label: "Peru Nuevo Sol", value: "PEN" },
  { label: "Philippines Peso", value: "PHP" },
  { label: "Poland Zloty", value: "PLN" },
  { label: "Portugal Escudo", value: "PTE" },
  { label: "Qatar Rial", value: "QAR" },
  { label: "Romania New Lei", value: "RON" },
  { label: "Russia Rouble", value: "RUB" },
  { label: "Rwanda Franc", value: "RWF" },
  { label: "Samoa Tala", value: "WST" },
  { label: "Sao Tome/Principe Dobra", value: "STD" },
  { label: "Saudi Arabia Riyal", value: "SAR" },
  { label: "Serbia Dinar", value: "RSD" },
  { label: "Seychelles Rupee", value: "SCR" },
  { label: "Sierra Leone Leone", value: "SLL" },
  { label: "Singapore Dollar", value: "SGD" },
  { label: "Slovakia Koruna", value: "SKK" },
  { label: "Slovenia Tolar", value: "SIT" },
  { label: "Solomon Islands Dollar", value: "SBD" },
  { label: "Somali Shilling", value: "SOS" },
  { label: "South Africa Rand", value: "ZAR" },
  { label: "South Korea Won", value: "KRW" },
  { label: "Spain Peseta", value: "ESP" },
  { label: "Sri Lanka Rupee", value: "LKR" },
  { label: "St Helena Pound", value: "SHP" },
  { label: "Sudan Pound", value: "SDG" },
  { label: "Suriname Dollar", value: "SRD" },
  { label: "Swaziland Lilangeni", value: "SZL" },
  { label: "Sweden Krona", value: "SEK" },
  { label: "Switzerland Franc", value: "CHF" },
  { label: "Syria Pound", value: "SYP" },
  { label: "Taiwan Dollar", value: "TWD" },
  { label: "Tanzania Shilling", value: "TZS" },
  { label: "Thailand Baht", value: "THB" },
  { label: "Tonga Pa'anga", value: "TOP" },
  { label: "Trinidad/Tobago Dollar", value: "EUR" },
  { label: "Tunisia Dinar", value: "TND" },
  { label: "Turkish New Lira", value: "TRY" },
  { label: "Turkmenistan Manat", value: "TMM" },
  { label: "Uganda Shilling", value: "UGX" },
  { label: "Ukraine Hryvnia", value: "UAH" },
  { label: "Uruguay Peso", value: "UYU" },
  { label: "United Arab Emirates Dirham", value: "AED" },
  { label: "Vanuatu Vatu", value: "VUV" },
  { label: "Venezuela Bolivar", value: "VEB" },
  { label: "Vietnam Dong", value: "VND" },
  { label: "Yemen Rial", value: "YER" },
  { label: "Zambia Kwacha", value: "ZMK" },
  { label: "Zimbabwe Dollar", value: "ZWD" }
export default listOfCurrencies;
